contexts:

  eagle_quick_go:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: fast
    time: 59
    cpu: 4
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container:  -H $PWD:/homeplaceholder
                            -B /tmp/lustre/plgtodrzygozdz
                            -B /home/plgrid/plgtodrzygozdz/subgoal_chess
                            -B /home/plgrid/plgtodrzygozdz/singularity_images
                            -B /tmp/lustre/plgtodrzygozdz/subgoal_chess_data
                            -B /home/plgrid/plgtodrzygozdz/chess_models
                            --env NEPTUNEPWD=$PWD  --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_8.08.2022.sif

  eagle_quick_tesla:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: tesla
    time: 59
    cpu: 4
    gpu: 1
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container: -H $PWD:/homeplaceholder
      -B /tmp/lustre/plgtodrzygozdz/
      -B /home/plgrid/plgtodrzygozdz/
      --env NEPTUNEPWD=$PWD  --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_8.08.2022.sif

  eagle_tesla:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: tesla
    time: 1440
    cpu: 4
    gpu: 1
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container: -H $PWD:/homeplaceholder
      -B /tmp/lustre/plgtodrzygozdz
      -B /home/plgrid/plgtodrzygozdz/
      --env NEPTUNEPWD=$PWD  --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_8.08.2022.sif

  entropy:
    account: students
    backend_type: slurm
    cmd_type: sbatch
    time: 4300
    cpu: 1
    gpu: 1
    mem: 16G
    nodes: 1
    ntasks: 1
    partition: common
    qos: 16gpu3d
    venv: /home/todrzygozdz/venvs/transformers
    slurm_url: todrzygozdz@entropy.mimuw.edu.pl
    storage_dir: /home/todrzygozdz/