contexts:

  eagle_quick_go:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: fast
    time: 59
    cpu: 4
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container:  -H $PWD:/homeplaceholder
                            -B $TMPDIR:/tmp
                            -B /tmp/lustre/plgtodrzygozdz
                            -B /home/plgrid/plgtodrzygozdz/subgoal_chess
                            -B /home/plgrid/plgtodrzygozdz/singularity_images
                            -B /tmp/lustre/plgtodrzygozdz/subgoal_chess_data
                            -B /tmp/lustre/plggracjangoral/leela_chess/mrunner_scratch/subgoal-chess/05_10-14_53-objective_feynman:/tress
                            -B /home/plgrid/plgtodrzygozdz/chess_models
                            --env NEPTUNEPWD=$PWD --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_09.10.2022.sif

  eagle_quick_go2:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: fast
    time: 59
    cpu: 4
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container:  -H $PWD:/homeplaceholder
                            -B /tmp/lustre/plggracjangoral/leela_chess/mrunner_scratch/subgoal-chess/05_10-14_53-objective_feynman:/trees
                            -B /tmp/lustre/plgtodrzygozdz/subgoal_chess_data/subgoal_leela_train/:/save_data
                            --env NEPTUNEPWD=$PWD --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_09.10.2022.sif

  eagle_data:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: standard
    time: 1440
    cpu: 1
    ntasks: 1
    mem: 60G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container:  -H $PWD:/homeplaceholder
                            -B /tmp/lustre/plggracjangoral/leela_chess/mrunner_scratch/subgoal-chess/05_10-14_53-objective_feynman:/trees
                            -B /tmp/lustre/plgtodrzygozdz/subgoal_chess_data/subgoal_leela_train/:/save_data
                            --env NEPTUNEPWD=$PWD --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_09.10.2022.sif

  eagle_quick_tesla:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: tesla
    time: 59
    cpu: 4
    gpu: 1
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container: -H $PWD:/homeplaceholder
      -B /tmp/lustre/plgtodrzygozdz/
      -B /home/plgrid/plgtodrzygozdz/
      --env NEPTUNEPWD=$PWD  --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_8.08.2022.sif

  eagle_alpacka_g:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: plgrid-long
    time: 10000
    cpu: 1
    mem: 30G
    nodes: 1
    slurm_url: plggracjangoral@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plggracjangoral/leela_chess
    singularity_container: -H $PWD:/homeplaceholder
      -B /home/plgrid/plggracjangoral/data/chess_database
      -B /home/plgrid/plggracjangoral/leela_weights
      -B /home/plgrid/plggracjangoral/leela
      --env NEPTUNEPWD=$PWD --nv /home/plgrid/plggracjangoral/singularity/transformers_26.09.2022.sif

  eagle_tesla:
    account: plgrlresearch
    backend_type: slurm
    cmd_type: sbatch
    partition: tesla
    time: 4300
    cpu: 4
    gpu: 1
    ntasks: 1
    mem: 120G
    nodes: 1
    slurm_url: plgtodrzygozdz@eagle.man.poznan.pl
    storage_dir: /tmp/lustre/plgtodrzygozdz/subgoal_chess
    singularity_container: -H $PWD:/homeplaceholder
      -B /tmp/lustre/plgtodrzygozdz
      -B /home/plgrid/plgtodrzygozdz/
      --env NEPTUNEPWD=$PWD  --nv /home/plgrid/plgtodrzygozdz/singularity_images/transformers_6.09.2022.sif

  entropy:
    account: students
    backend_type: slurm
    cmd_type: sbatch
    time: 4300
    cpu: 1
    gpu: 1
    mem: 16G
    nodes: 1
    ntasks: 1
    partition: common
    qos: 4gpu4d
    slurm_url: todrzygozdz@entropy.mimuw.edu.pl
    storage_dir: /home/todrzygozdz/
    singularity_container: -H $PWD:/homeplaceholder
      -B /home/todrzygozdz/
      --env NEPTUNEPWD=$PWD  --nv /home/todrzygozdz/singularity_images/transformers_5.09.2022.sif